#! /usr/bin/env python3
"""HOMEINFO events daemon."""

from hievents.config import CONFIG
from hievents.wsgi import APPLICATION


if __name__ == '__main__':
    HOST = CONFIG['wsgi']['host']
    PORT = int(CONFIG['wsgi']['port'])
    APPLICATION.run(host=HOST, port=PORT)
